########################### NETWORKS
networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
  pelican:
    name: pangolin_pelican
    external: true

########################### VOLUMES
volumes:
  data:
  logs:

########################### SERVICES
services:
  panel:
    container_name: pelican-panel
    image: ghcr.io/pelican/panel:latest
    restart: always
    hostname: pelican-panel
    networks:
      - default
      - pelican
#    ports:
#      - 80:80
#      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - data:/pelican-data
      - logs:/var/www/html/storage/logs
      - ./appdata/Caddyfile:/etc/caddy/Caddyfile
    environment:
      XDG_DATA_HOME: /pelican-data
      APP_URL: ${APP_URL}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
