name: pangolin

########################### NETWORKS
networks:
  default:
    driver: bridge
    name: pangolin_frontend

########################### VOLUMES
volumes:
  pangolin-data: null

########################### SERVICES
services:
  pangolin:
    image: docker.io/fosrl/pangolin:ee-1.21.1
    container_name: pangolin
    restart: always
    deploy:
      resources:
        limits:
          memory: 2g
        reservations:
          memory: 512m
    volumes:
      - ./appdata/config:/app/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      interval: "10s"
      timeout: "10s"
      retries: 15

  gerbil:
    image: docker.io/fosrl/gerbil:1.4.3
    container_name: gerbil
    restart: always
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --reachableAt=http://gerbil:3004
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/
    volumes:
      - ./appdata/config:/var/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
      - 21820:21820/udp
      - 443:443
      - 443:443/udp # For http3 QUIC if desired
      - 80:80

  traefik:
    image: docker.io/traefik:v3.7
    container_name: traefik
    restart: always
    network_mode: service:gerbil # Ports appear on the gerbil service
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    volumes:
      - ./appdata/config/traefik:/etc/traefik:ro # Volume to store the Traefik configuration
      - ./appdata/config/letsencrypt:/letsencrypt # Volume to store the Let's Encrypt certificates
      - ./appdata/config/traefik/logs:/var/log/traefik # Volume to store Traefik logs

  crowdsec:
    command: -t
    container_name: crowdsec
    environment:
      COLLECTIONS: crowdsecurity/traefik crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules crowdsecurity/linux crowdsecurity/iptables
      ENROLL_INSTANCE_NAME: pangolin-crowdsec
      ENROLL_TAGS: docker
      GID: "1000"
      PARSERS: crowdsecurity/whitelists
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 30s
      test:
        - CMD
        - cscli
        - lapi
        - status
      timeout: 5s
    image: docker.io/crowdsecurity/crowdsec:latest-debian
    labels:
      - traefik.enable=false
    ports:
      - 6060:6060
    restart: always
    volumes:
      - ./appdata/config/crowdsec:/etc/crowdsec
      - ./appdata/config/crowdsec/db:/var/lib/crowdsec/data
      - ./appdata/config/traefik/logs:/var/log/traefik:ro
      - /var/log/journal:/var/log/host:ro
