########################### NETWORKS
networks:
  <container>:
    name: <container>

########################### LOCKDOWN
x-lockdown: &lockdown
  read_only: true
  security_opt:
    - "no-new-privileges=true"

########################### SERVICES
services:
  newt:
    container_name: newt-<host>
    image: fosrl/newt
    restart: always
    <<: *lockdown
    read_only: true
    user: ${PUID}:${PGID}
    networks:
      - <container>
    environment:
      PANGOLIN_ENDPOINT: ${PANGOLIN_ENDPOINT}
      NEWT_ID: ${NEWT_ID}
      NEWT_SECRET: ${NEWT_SECRET}
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 500M
        reservations:
          cpus: '0.20'
          memory: 250M
