########################### NETWORKS
networks:
  nextcloud:
     external: true

########################### VOLUMES
volumes:
  nextcloud:
  nc-data:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.20.200,soft,nfsvers=4"
      device: ":/Nextcloud"
  # MariaDB
  etc:
  var:
  cmd:
  backup:

########################### LOCKDOWN
x-lockdown: &lockdown
  # prevents write access to the image itself
  read_only: true
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"

########################### SERVICES
services:
  mariadb:
    image: 11notes/mariadb:11.4.5
    restart: always
    <<: *lockdown
    tmpfs:
      # needed for read-only file system to work
      - "/run/mariadb:uid=${PUID},gid=${PGID}"
    volumes:
      - etc:/mariadb/etc
      - var:/mariadb/var
      - backup:/mariadb/backup
      - cmd:/run/cmd
    environment:
      - TZ=${TZ}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}

  cron:
    image: "11notes/cron:4.6"
    restart: "always"
    environment:
      TZ: ${TZ}
      # run backup every day at 03:00
      CRONTAB: |-
        0 3 * * * cmd-socket '{"bin":"backup"}' > /proc/1/fd/1
    volumes:
      - "cmd:/run/cmd"
    depends_on:
      mariadb:
        condition: "service_healthy"
        restart: true

  nextcloud:
    image: nextcloud:latest
    restart: always
    user: ${PUID}:${PGID}
    ports:
      - 8080:80
    links:
      - mariadb
    volumes:
      - nextcloud:/var/www/html
      - nc-data:/data
    environment:
      - TZ=${TZ}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=mariadb
      - MYSQL_HOST=mariadb
    depends_on:
      mariadb:
        condition: "service_healthy"
        restart: true

  collabora:
    image: collabora/code:latest
    restart: always
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
      - extra_params=--o
      - ssl.enable=false
      - user_interface.use_integration_theme=false
