########################### NETWORKS
networks:
  grocy:
    external: true

########################### VOLUMES
volumes:
  config:

########################### SERVICES
services:
  grocy:
    container_name: grocy
    image: lscr.io/linuxserver/grocy:latest
    restart: unless-stopped
    networks:
      - grocy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - config:/config
    ports:
      - 9283:80
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          cpus: '0.10'
          memory: 50M
