########################### NETWORKS
networks:
  grocy:
    external: true

########################### VOLUMES
volumes:
  config:

########################### LOCKDOWN
x-lockdown: &lockdown
  read_only: true
  security_opt:
    - "no-new-privileges=true"

########################### SERVICES
services:
  grocy:
    container_name: grocy
    image: lscr.io/linuxserver/grocy:latest
    restart: unless-stopped
    <<: *lockdown
    user: ${PUID}:${PGID}
    networks:
      - grocy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - config:/config
    ports:
      - 9283:80
