# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
search:
  autocomplete: "google"
  favicon_resolver: "google"
ui:
  infinite_scroll: true
  theme_args:
    # style of simple theme: auto, light, dark, black
    simple_style: black
outgoing:
  request_timeout: 10.0
  proxies:
    all://:
      - socks5h://tor:9050
  using_tor_proxy: true
engines:
  - name: bing
    engine: bing
    shortcut: bi
    disabled: false
