########################### NETWORKS
networks:
  pangolin:
    external: true
  media-management:
    external: true

########################### VOLUMES
volumes:
  app.server:
  app.configs:
  app.logs:
  transcode_cache:
  media:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.20.200,soft,nfsvers=4"
      device: ":/Media"

########################### SERVICES
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=7
      - nodeName=MyInternalNode
      - auth=false
      - openBrowser=true
      - maxLogSizeMB=10
      - cronPluginUpdate=
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - app.server:/app/server
      - app.configs:/app/configs
      - app.logs:/app/logs
      - media:/media
      - transcode_cache:/temp

    devices:
      - /dev/dri:/dev/dri

  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: service:tdarr
    environment:
      - TZ=Europe/London
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - nodeName=MyExternalNode
      - serverIP=0.0.0.0
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=7
      - nodeType=mapped
      - priority=-1
      - cronPluginUpdate=
      - apiKey=${API_KEY}
      - maxLogSizeMB=10
      - pollInterval=2000
      - startPaused=false
      - transcodegpuWorkers=3
      - transcodecpuWorkers=0
      - healthcheckgpuWorkers=1
      - healthcheckcpuWorkers=0
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all

    volumes:
      - app.configs:/app/configs
      - app.logs:/app/logs
      - media:/media
      - transcode_cache:/temp

    devices:
      - /dev/dri:/dev/dri
