########################### NETWORKS
networks:
  jellyfin:
     external: true

########################### VOLUMES
volumes:
  jellyfin-config:
  jellyfin-cache:
  media:
    driver_opts:
      type: "nfs"
      o: "addr=10.0.20.200,soft,nfsvers=4"
      device: ":/Media"

########################### SERVICES
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    restart: unless-stopped
    user: ${PUID}:${PGID}
    group_add:
      - '<group render>'
    networks:
      - jellyfin
    ports:
      - '127.0.0.1:8096:8096'
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - media:/media
    environment:
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_PUBLISHEDSERVERURL}

# GPU setup
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 #Intel QSV
